function frame_plot(x,y,z,T,N,down_sampling)

v1 = 1:down_sampling:length(x); % Down-sample arrow plotting.
%plot3(x,y,z,'k','LineWidth',3);
hold on;
h(1) = quiver3(x(v1)',y(v1)',z(v1)',...
    T(v1,1),T(v1,2),T(v1,3),...
    .5,'color', 'black','LineWidth',1);
h(2) = quiver3(x(v1)',y(v1)',z(v1)',...
    N(v1,1),N(v1,2),N(v1,3),...
    .5,'color', 'blue','LineWidth',1);
legend(h,{'Tangent','Normal'},'Location','southoutside',...
    'Orientation','Horizontal',...
    'Interpreter','latex');
grid on;
end

